version: "3.4"

services:
  mosquitto:
    build:
      context: ./src/containers/mqtt
    image: mqtt
    ports:
      - "1883:1883"
    expose:
      - "1883"
    restart: unless-stopped
    
networks: 
  default: 
    driver: bridge